"""
This file was auto-generated by djelm {{cookiecutter.version}}

For the best developer experience ensure the following:

- {{cookiecutter.program_name}}Flags variable is not renamed.
- The key variable value "{{cookiecutter.scope}}-djelmwidget-{{cookiecutter.program_name}}" is not modified
"""

from djelm.flags import Flags, IntFlag

key = "{{cookiecutter.scope}}-djelm-{{cookiecutter.view_name}}"

{{cookiecutter.program_name}}Flags = Flags(IntFlag())
