FROM ubuntu:22.04

# Install build dependencies
RUN apt-get update -y && apt-get install -qq apt-transport-https apt-utils software-properties-common
RUN apt install -y python3.11 python3-pip
RUN apt -y upgrade
