"""
This file was auto-generated by djelm 0.21.0

For the best developer experience ensure the following:

- MainFlags variable is not renamed.
- The key variable value "elmprogramsmain-djelmwidget-Main" is not modified
"""

from djelm.flags import Flags, IntFlag

key = "elmprogramsmain-djelm-Main"

MainFlags = Flags(IntFlag())
