"""
This file was auto-generated by djelm 0.21.0

For the best developer experience ensure the following:

- ModelChoiceFieldFlags variable is not renamed.
- The key variable value "widgetselmprogramsmodelchoicefield-djelmwidget-ModelChoiceField" is not modified
"""

from djelm.flags import Flags
from djelm.flags.form import ModelChoiceFieldFlag

key = "widgetselmprogramsmodelchoicefield-djelmwidget-Modelchoicefield"

ModelChoiceFieldFlags = Flags(ModelChoiceFieldFlag())
