"""
This file was auto-generated by djelm 0.21.0

For the best developer experience ensure the following:

- ModelMultipleChoiceFieldFlags variable is not renamed.
- The key variable value "widgetselmprogramsmodelmultiplechoicefield-djelmwidget-ModelMultipleChoiceField" is not modified
"""

from djelm.flags import Flags
from djelm.flags.form import ModelMultipleChoiceFieldFlag

key = "widgetselmprogramsmodelmultiplechoicefield-djelmwidget-Modelmultiplechoicefield"

ModelMultipleChoiceFieldFlags = Flags(ModelMultipleChoiceFieldFlag())
