module Widgets.Models.ModelMultipleChoiceField exposing (..)

{-| Do not manually edit this file, it was auto-generated by djelm
<https://github.com/Confidenceman02/django-elm>
-}

import Json.Decode as Decode
import Json.Decode.Pipeline exposing (required, optional, hardcoded)


type alias ToModel =
    { help_text : String
    , auto_id : String
    , id_for_label : String
    , label : Maybe String
    , name : String
    , widget_type : String
    , options : List Options_
    }

type alias Options_ =
    { choice_label : String
    , value : String
    , selected : Bool
    }


toModel : Decode.Decoder ToModel
toModel =
    Decode.succeed ToModel
        |> required "help_text" Decode.string
        |> required "auto_id" Decode.string
        |> required "id_for_label" Decode.string
        |> required "label" (Decode.nullable Decode.string)
        |> required "name" Decode.string
        |> required "widget_type" Decode.string
        |> required "options" (Decode.list options_Decoder)

options_Decoder : Decode.Decoder Options_
options_Decoder =
    Decode.succeed Options_
        |> required "choice_label" Decode.string
        |> required "value" Decode.string
        |> required "selected" Decode.bool
